language: node_js
node_js:
  - "5"
sudo: false
install:
    - npm install -g babel-cli
    - npm install
script: "make test"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
